### ISSUE TITLE
[Feature]: Add a "type" for Input

### ISSUE THREAD

**Issue by maelp** [radix-vue/shadcn-vue#168]
### Describe the feature

Input expects a "string | number" as modelValue, but forces a `type="text"`, we could replace it that way to allow for both

```
<script setup lang="ts">
import { defineProps, defineEmits, withDefaults } from "vue";
import { useVModel } from "@vueuse/core";
import { cn } from "../frameworkUtils";

const props = withDefaults(
  defineProps<{
    defaultValue?: string | number;
    modelValue?: string | number;
    type?: "text" | "number";
  }>(),
  { type: "text" }
);

const emits = defineEmits<{
  (e: "update:modelValue", payload: string | number): void;
}>();

const modelValue = useVModel(props, "modelValue", emits, {
  passive: true,
  defaultValue: props.defaultValue,
});
</script>

<template>
  <input
    v-model="modelValue"
    :type="type"
    :class="
      cn(
        'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
        $attrs.class ?? ''
      )
    "
  />
</template>

```

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by olemarius** [comment]
```html
<Input type="number" /> ` 
```

type attribute will be inherited as long as it's not disabled with
```js
defineOptions({
    inheritAttrs: false,
})
```

**Comment by sadeghbarati** [comment]
Mael wants **autocomplete props suggestion** inside VSCode with <kbd>Ctrl + Space</kbd>


Since `defineProps` doesn't support complex types, 
We can't use these types from Vue `IntrinsicElementAttributes['input']` or `InputHTMLAttributes`

There is a plugin to resolve this issue but we want it inside Vue itself instead of another plugin
https://github.com/unplugin/unplugin-vue-complex-types


[Vue playground example](https://play.vuejs.org/#eNrVVc1S2zAQfhXV0xknTCJD6ck14a/pQKe0TKHtAXNw7E0Q2JJHkkmYTN69K8mxY6Dpoace7ES7q91vv/3x0jsuS/pYgRd6kUolKzXJEz47iD2tYo8o0FU5ijkrSiE1WRIJU7IiUykK4uM1v1Fd4W8OJ5XWgtd6GmwKTRT/Q2P/zLJrE/NUcKVJoWbkwMSMlJaMz0Y9/wzyXJBfQubZG78f8yhwsBEkHjRgwEQDngiJOpjSPFEK85rMhpO8guHe7m7sBc5w08RKSI3PamtwqIiCJoA38FwmwyIp6b0SHClcGvu4ViB/IbESI0tztTCC2LvTulRhEMwSvFYWlImAl0VoDI7e0V26G2RM6cCcaXGPXgZrHzph+ZzxbFiAnMFWb13Toz26937tuKtyIUyEVcxXmJVWyP2UzZ7llIqiZDnIb6VmWJtObgmWZP7ZyrSsoMGb3kH68Ir8fk3FpQQF8hFT2cgRQWmnHl99hQX+b5SFyKq8TvwPyu+gRF4ZjM7spOIZwt6ws2jPbYmwpa7VeKGBq3VSBqhlw9rHHnbk6ZbUW7j7dH+DxbafX5+sUSybUdBPJeBouStn1xdfjjV2+6TSoAbknJvOVywd51AA162uO4fozjzBDhlLKWRIbo5QHqzLNlTT9JZ8wtJDRrTAmUKaHoEghcAzRSaJAguE7gTGDywsNMY1yGmSArmUolSN+WtYkRS8SBJ1GBI3rua8Mq92SGuYW3ZNy8vSMXNqpvJngjM7wAlViyZvc7CJt/bzC9PTjUW31RuSphVPTSlJynuUUsbLSqtwI9DNbb/OBonSleRrzz0Ts+cu9PtNfuZxG6u0NB2QOdN3H2GaVLlWvQymjINlMLLvUa8/aOgKiY/8IZ0W38p6rUuJFaw9ZoCUViliQV7JzcvS/jAlg1RjeR/gaS5kZgjChHzaoltiOEMiipGjf0bpWuVlcdstbCmMDFLBsXlJyMwKtinRxBQd155by1gKH1ezhMxsZn/g8qZW3a/nxYxcpHKhCe5t59qyYH1bSXdBP//8bP/I/Y+N91fukSJXti1Mv01whmuqyeEh8fG76o02yYsC5+QFx6vfzhriMQ==)
