### ISSUE TITLE
[Bug]: Some components need whitespace-nowrap

### ISSUE THREAD

**Issue by anonimusprogramus** [radix-vue/shadcn-vue#199]
### Environment

```bash
Developement/Production OS: Linux Mint 20.1 Cinnamon
Node version: v18.16.0
Package manager: pnpm@8.9.2
Radix Vue version: 1.1.1
Shadcn Vue version: 0.8.2
Vue version: 3.3.7
Nuxt version: 3.8.0
Nuxt mode: universal
Nuxt target: client server
CSS framework: tailwindcss@3.3.3
Client OS: Linux Mint 20.1 Cinnamon
Browser: Brave 1.60
```

### Link to minimal reproduction

https://www.shadcn-vue.com/themes

### Steps to reproduce

1. Open [themes page](https://www.shadcn-vue.com/themes)
2. Resize to `xl` or `md` screen size
3. Reload the page
4. For miliseconds you'll see Button's title `"Copy code"` being **wrapped**

![2023-12-01 10-52-14](https://github.com/radix-vue/shadcn-vue/assets/7464749/61dfe966-9fea-44f9-af15-4a6d0abcd670)

### Describe the bug

Title having spaces may be wrapped because of missing `whitespace-nowrap` class.

In [shadcn](https://github.com/shadcn-ui/ui/tree/main/apps/www/registry/new-york/ui), following (new-york) components have `whitespace-nowrap`:
- button
- select
- tabs

Meanwhile, in [shadcn-vue](https://github.com/radix-vue/shadcn-vue/tree/dev/apps/www/src/lib/registry/new-york/ui) only these:
- table
- tabs

![2023-12-02 11-04-57](https://github.com/radix-vue/shadcn-vue/assets/7464749/caf8da51-b627-4627-937a-6831d8e67d0c)

![2023-12-02 11-05-12](https://github.com/radix-vue/shadcn-vue/assets/7464749/438d7c99-ebc9-4bbc-bcb9-c7f0cfa9965a)

### Expected behavior

No wrap

**Comment by sadeghbarati** [comment]
https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/.vitepress/theme/components/PageHeaderDescription.vue#L7C1-L9C18

I think `WrapBalancer` cause the layout shifts

**Comment by anonimusprogramus** [comment]
Agree about that layout shift.

I looked into shadcn, looks like thay had the [same problem](https://github.com/shadcn-ui/ui/commits/main/apps/www/registry/new-york/ui/button.tsx) and fixed it on Oct 21 by adding `whitespace-nowrap`

If we're gonna fix this, should [button.json](https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/public/registry/styles/new-york/button.json) be fixed too?

**Comment by sadeghbarati** [comment]
looked into [`shadcn-ui`](https://github.com/search?q=repo%3Ashadcn-ui%2Fui%20whitespace-nowrap&type=code)

- button
- select
- tab

has `whitespace-nowrap` thanks for report

PR welcomed if you have time 🙏 

---

If you start doing it please refactor the button to use `VariantProps` from `class-variance-authority` instead of `NonNullable<Parameters<typeof buttonVariants>`

**Comment by adirizky54** [comment]
@sadeghbarati I'm agree with you to use `VariantProps` instead of `NonNullable<Parameters<typeof buttonVariants>`, but 
Type version of defineProps isn't smart enough to resolve more complicated types in Vue, and you will getting error like this.

<img width="856" alt="Screenshot 2023-12-03 at 16 42 40" src="https://github.com/radix-vue/shadcn-vue/assets/24888851/c43d0442-3e21-43a9-98d3-7670da3ea038">

**Comment by sadeghbarati** [comment]
Ow man you right 😭, but how [Svelte example](https://github.com/joe-bell/cva/blob/main/examples/svelte/src/components/button.svelte#L21) support complex types?

```ts
export type VariantProps<Component extends (...args: any) => any> = Omit<OmitUndefined<Parameters<Component>[0]>, "class" | "className">;
```

---

Looks like we have to use it this way before complex types support

https://github.com/joe-bell/cva/blob/main/examples/vue/src/components/Button.vue

**Comment by adirizky54** [comment]
https://vuejs.org/guide/typescript/composition-api.html#syntax-limitations

**Comment by hrynevychroman** [comment]
Started working on this 🙂

**Comment by hrynevychroman** [comment]
@sadeghbarati Hello 👋 

Have one question about it, I don't think that it is great to use `whitespace-nowrap` on Select for example, because if selected text will be wider it will overlap 👇 

<img width="558" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/82209198/a43adcff-a563-4854-9cfe-298af0e63705">


So my solution is to change Select from `flex` to `grid`, so we can `truncate` selected text, what do you think? 👇 

<img width="553" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/82209198/89d1038a-94a9-46fd-88c4-01a8e96237b3">

**Comment by hrynevychroman** [comment]
Please Assign me for this Issue, I already change Button with refactor `VariantProps` ❤️

**Comment by hrynevychroman** [comment]
One more question, sorry, I need to make PR when everything will be fixed, or better do it now and push new commits?

Working Branch: https://github.com/romanhrynevych/shadcn-vue/tree/199-bug-whitespace-nowrap

**Comment by sadeghbarati** [comment]
It's up to you, PR Title is important 

of course, individual commit messages are important but not as much as the first commit and PR Title
