### ISSUE TITLE
[Feature]: How can i close Dialog using method not DialogClose element ?

### ISSUE THREAD

**Issue by prdip** [radix-vue/shadcn-vue#314]
### Describe the feature

I want to close Dialog box using custom method 

```
 methods: { 
            close(){
                close current dialog   
            },
```

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
You can remove `DialogClose` component
and Control the `Dialog` it with simple state management like Vue `refs` or `pinia` stores

**Comment by prdip** [comment]
Can you share example using Vue refs here  ?
@sadeghbarati

**Comment by sadeghbarati** [comment]
@prdip 

see composable dir and then wash your eyes 😄 

https://stackblitz.com/edit/tcupzq?file=src%2FApp.vue

**Comment by prdip** [comment]
Thanks for opening my eyes....... @sadeghbarati 🤓

**Comment by taufikmuharrom** [comment]
thanks a lot @sadeghbarati 👏

**Comment by pwendell256** [comment]
Hi, sorry for the inconvenience. Do you have any idea how I can close the dialogue by clicking the submit form?

**Comment by milos018** [comment]
@pwendell256 
You would have a ref - you can name it const isDialogOpen = ref(false) (it must be a boolean) in the <script setup>.
Once you submit the form and all goes well, all you have to do is say isDialogOpen.value = false.
Don't forget to have <Dialog v-model:open="isDialogOpen"> ... otherwise it won't work...

Hope that helps!
Milos
