### ISSUE TITLE
[Documentation] Is the global css address specified for the Vite setup incorrect?

### ISSUE THREAD

**Issue by p74DDone** [radix-vue/shadcn-vue#514]
I was trying to get shadcn-vue setup last night following the Vite guide at https://www.shadcn-vue.com/docs/installation/vite.html.

I deleted the default style as per step 5:

> Delete the default Vite stylesheet ./src/style.css

For the global css file in step 7 it says to specify src/index.css:

> Where is your global CSS file? › › src/index.css

However in step 8 it says to remove .style.css and add ./assets/index.css:

> import { createApp } from 'vue'
> - import './style.css'
> import App from './App.vue'
> + import '**./assets/index.css'**

At least during my walkthrough of that guide, assets/index.css didn't exist. I changed this to src/index.css and everything started working as expected.

**Comment by sadeghbarati** [comment]
@p74DDone 

`shadcn-vue` installation is about starting with Vite/Nuxt/Astro/Laravel + TailwindCSS around shadcn components


```Where is your global CSS file? » src/assets/index.css```

**shadcn-vue CLI** default `path` for creating Tailwind CSS file is ` src/assets/index.css` 
Which is not exist yet until you complete CLI steps

**Comment by fervflow** [comment]
@p74DDone 
When you run the init command `npx shadcn-vue@latest init` the CLI ask you where is/will be located your global CSS file, if there is no such file it will be created. Also, it will generate `tailwind.config.js` if you did not already; because you can notice there is no `npx tailwindcss init -p` step in the guide.

But if you already have installed `tailwindcss` from tailwind's installation guide, you can choose the CSS file specified there, where you only have `@tailwind base; @tailwind components; @tailwind utilities;`, just specify it in the shadcn-vue CLI, then, import it in your main/index ts/js file. 

Btw, if you want to use the [shadcn themes](https://www.shadcn-vue.com/themes) you may choose to use CSS variables at the moment of installing shadcn-vue.

**Comment by sadeghbarati** [comment]
"It's worth noting that you're not required to place your main file in `src/assets/index.css`; you can place it anywhere you prefer. However, before running your app using the CLI, it's necessary to create essential files for your setup."
