### ISSUE TITLE
[Bug]: The Scroll-area doesn't work with max-height, only with height.

### ISSUE THREAD

**Issue by Grinch3214** [radix-vue/shadcn-vue#593]
### Reproduction

https://stackblitz.com/run?file=src%2FApp.vue

### Describe the bug

The Scroll-area doesn't work with max-height, only with height.

Instead of h-72 in the ScrollArea component, use max-h-72.

This is a very useful value that saves you from writing your own code to calculate the height of elements when it's not needed.
![Screenshot_1](https://github.com/radix-vue/shadcn-vue/assets/78050226/c4a3c2b1-cf7d-41d7-b9df-243ba0565668)

### System Info

```bash
shadcn-nuxt
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by hrynevychroman** [comment]
@Grinch3214 Reproduction don't valid ☺️

**Comment by sadeghbarati** [comment]
@Grinch3214 Hi you need to set height, it's required for `ScrollArea` component

https://stackblitz.com/edit/bthdwy?file=src%2FApp.vue

If you look for `data-scrollbarimpl` element in Devtools, it's outside of `data-radix-scroll-area-viewport` element
so in order to get the corrent height calculation you need to add height to the `ScrollArea` component
